version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./Backend:/app
    restart: unless-stopped
    command: >
      /bin/sh -c "
        # Remove old containers/images before starting
        docker system prune -af || true &&
        uvicorn fastapi_main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: ./UI_Copy/NewKnowledgeAssist
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./UI_Copy/NewKnowledgeAssist:/app
    restart: unless-stopped
    command: >
      /bin/sh -c "
        # Remove old containers/images before starting
        docker system prune -af || true &&
        npm run start
      "

# Optional: Cleanup network and unused volumes when starting
networks:
  default:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
