version: '3.9'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./Backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./FrontEnd/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
