version: "3.9"

services:
  backend:
    image: 361568250748.dkr.ecr.us-west-1.amazonaws.com/itopsbackend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      VAULT_TOKEN: "${VAULT_TOKEN}"
    restart: unless-stopped

  frontend:
    image: 361568250748.dkr.ecr.us-west-1.amazonaws.com/itopsfrontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
