name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1
      ECR_BACKEND_REPO: 361568250748.dkr.ecr.us-west-1.amazonaws.com/itopsbackend
      ECR_FRONTEND_REPO: 361568250748.dkr.ecr.us-west-1.amazonaws.com/itopsfrontend
      EC2_USER: ubuntu
      EC2_HOST: ${{ secrets.EC2_HOST }}   # Public IP or hostname of your EC2
      SSH_KEY: ${{ secrets.EC2_SSH_KEY }} # Private key stored in GitHub Secrets

    steps:
      # -------------------------------
      # Checkout repo
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # Configure AWS CLI
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------------
      # Login to AWS ECR
      # -------------------------------
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_BACKEND_REPO
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_FRONTEND_REPO

      # -------------------------------
      # Build Docker images
      # -------------------------------
      - name: Build backend image
        run: |
          docker build -t itopsbackend:latest Backend/
          docker tag itopsbackend:latest $ECR_BACKEND_REPO:latest

      - name: Build frontend image
        run: |
          docker build -t itopsfrontend:latest UI_Copy/
          docker tag itopsfrontend:latest $ECR_FRONTEND_REPO:latest

      # -------------------------------
      # Push Docker images to ECR
      # -------------------------------
      - name: Push backend image
        run: docker push $ECR_BACKEND_REPO:latest

      - name: Push frontend image
        run: docker push $ECR_FRONTEND_REPO:latest

      # -------------------------------
      # Deploy to EC2
      # -------------------------------
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            # Clean up old containers and images
            docker rm -f backend frontend || true
            docker system prune -af || true

            # Pull latest images
            docker pull $ECR_BACKEND_REPO:latest
            docker pull $ECR_FRONTEND_REPO:latest

            # Run backend container
            docker run -d --name backend -p 8000:8000 \
              -e VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}" \
              $ECR_BACKEND_REPO:latest

            # Run frontend container
            docker run -d --name frontend -p 80:80 $ECR_FRONTEND_REPO:latest
